server:
  port: 8091
spring:
  application:
    name: tm-rest-service
  datasource:
    url: jdbc:mysql://localhost/tmservice
    username: ea
    password: PassYes@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    
    
    

